baseURL = 'https://xgtbz.github.io/xgtbzblog/'
languageCode = 'en-us'
title = 'xgtbz'
theme = 'hugo-blog-awesome'


[[params.socialIcons]]
name = "github"
url = "https://github.com/xgtbz"

[params]
  toc = true
  tocOpen = true
