baseURL = 'https://xgtbz.github.io/xgtbzblog/'
languageCode = 'en-us'
title = 'R'
theme = 'hugo-blog-awesome'
publishDir = "docs"


[[params.socialIcons]]
name = "github"
url = "https://github.com/xgtbz"

[params]
  toc = true
  author.name = "xgtbz"
  tocOpen = true